[env]
TERM = "xterm-256color"

[general]
import = [
  '~/.config/alacritty/themes/themes/catppuccin_latte.toml'
]

[font]
size = 16
normal = { family = "Hack Nerd Font Mono" }

[window]
opacity = 0.85
