[settings]
dotfiles.default_mode = "symlink"

[tools]
ghq = "latest"
helix = "latest"
herdr = "latest"
node = "latest"
pnpm = "latest"
starship = "latest"
github-cli = "latest"
fzf = "latest"
hunk = "latest"
eza = "latest"
zoxide = "latest"
ripgrep = "latest"
fd = "latest"
bat = "latest"
codex = "latest"
yazi = "latest"
lazygit = "latest"
"github:mickael-menu/zk" = "latest"
rust = "latest"
cmake = "latest"
gitui = "latest"
glow = "latest"

[dotfiles]
"~/.agents" = { source = "home/.agents" }
"~/.config/ghostty" = "home/.config/ghostty"
"~/.config/git" = "home/.config/git"
"~/.config/helix" = "home/.config/helix"
"~/.config/herdr/config.toml" = "home/.config/herdr/config.toml"
"~/.config/lazygit" = { source = "home/.config/lazygit" }
"~/.config/mise/config.toml" = "mise.toml"
"~/.config/mise/mise.linux.toml" = "mise.linux.toml"
"~/.config/mise/mise.macos.toml" = "mise.macos.toml"
"~/.config/nvim" = { source = "home/.config/nvim" }
"~/.config/starship.toml" = { source = "home/.config/starship.toml" }
"~/.config/yazi" = { source = "home/.config/yazi" }
"~/.zshrc" = "home/.zshrc"
