[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'

[[plugins]]
repo = 'Shougo/dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = [
  'denops.vim',
  'ddc-ui-native',
  'ddc-source-lsp',
  'ddc-source-around',
  'ddc-filter-sorter_rank',
  'ddc-filter-matcher_head',
  'denops-popup-preview.vim',
  'denops-signature_help',
]

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'

[[plugins]]
repo = 'matsui54/denops-signature_help'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = [
  'vim-airline-themes',
]

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'

[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'
