[[plugins]]
repo = 'Shougo/dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
source ~/.config/vim/rc/plugins/ddc.vim
'''

[[plugins]]
repo = 'Shougo/ddc-ui-pum'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
source ~/.config/vim/rc/plugins/lsp.vim
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_lsp_kind'

[[plugins]]
repo = 'Shougo/ddu.vim'
hook_add = '''
source ~/.config/vim/rc/plugins/ddu.vim
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-column-filename'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'uga-rosa/ddu-filter-converter_devicon'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/vim/rc/plugins/gitgutter.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
let ayucolor = 'light'
colorscheme ayu
'''

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
