let g:mapleader = ' '

filetype plugin indent on

set nowritebackup
set nobackup
set noswapfile
set nocompatible
set mouse=a
set ambiwidth=double "全角文字用設定
set noerrorbells
set re=2
set smartindent
set autoindent
set clipboard+=unnamed
set signcolumn=yes
set termguicolors
set ignorecase
set smartcase
set wrapscan
set incsearch
set hlsearch
set virtualedit=block

nnoremap <leader>bx <CMD>bd<CR>
nnoremap <leader>bn <CMD>bn<CR>
nnoremap <leader>bp <CMD>bp<CR>

const s:dpp_base = '~/.cache/vim/dpp/'
const s:dpp_config = '~/.config/vim/dpp.ts'

const s:denops_src = s:dpp_base .. 'repos/github.com/vim-denops/denops.vim'
const s:denops_hello = s:dpp_base .. 'repos/github.com/vim-denops/denops-helloworld.vim'

const s:dpp_src = s:dpp_base .. 'repos/github.com/Shougo/dpp.vim'
const s:dpp_installer = s:dpp_base .. 'repos/github.com/Shougo/dpp-ext-installer'
const s:dpp_lazy = s:dpp_base .. 'repos/github.com/Shougo/dpp-ext-lazy'
const s:dpp_toml = s:dpp_base .. 'repos/github.com/Shougo/dpp-ext-toml'
const s:dpp_git = s:dpp_base .. 'repos/github.com/Shougo/dpp-protocol-git'

execute 'set runtimepath+=' .. s:denops_src
execute 'set runtimepath+=' .. s:denops_hello

execute 'set runtimepath+=' .. s:dpp_src
execute 'set runtimepath+=' .. s:dpp_installer
execute 'set runtimepath+=' .. s:dpp_lazy
execute 'set runtimepath+=' .. s:dpp_toml
execute 'set runtimepath+=' .. s:dpp_git

if s:dpp_base->dpp#min#load_state()
  autocmd User DenopsReady
  \ : echohl WarningMsg
  \ | echomsg 'dpp load_state() is failed'
  \ | echohl NONE
  \ | call dpp#make_state(s:dpp_base, s:dpp_config)
endif

autocmd User Dpp:makeStatePost
  \ : echohl WarningMsg
  \ | echomsg 'dpp make_state() is done'
  \ | echohl NONE

if has('syntax')
  syntax on
endif
