set nocompatible

const g:mapleader = "\<Space>"

set termguicolors
set signcolumn=yes
set updatetime=100
set encoding=UTF-8
set nowritebackup
set nobackup
set virtualedit=block
set ambiwidth=double
set ignorecase
set smartcase
set wrapscan
set incsearch
set hlsearch
set noerrorbells
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set smartindent
set noswapfile
set mouse=a

const s:denops_src = '~/.cache/dpp/repos/github.com/vim-denops/denops.vim'
const s:denops_hello = '~/.cache/dpp/repos/github.com/vim-denops/denops-helloworld.vim'

execute 'set runtimepath+=' .. s:denops_src
execute 'set runtimepath+=' .. s:denops_hello

const s:dpp_src = '~/.cache/dpp/repos/github.com/Shougo/dpp.vim'
const s:dpp_ext_installer = '~/.cache/dpp/repos/github.com/Shougo/dpp-ext-installer'
const s:dpp_ext_lazy = '~/.cache/dpp/repos/github.com/Shougo/dpp-ext-lazy'
const s:dpp_ext_toml = '~/.cache/dpp/repos/github.com/Shougo/dpp-ext-toml'
const s:dpp_prot_git = '~/.cache/dpp/repos/github.com/Shougo/dpp-protocol-git'

execute 'set runtimepath+=' .. s:dpp_src
execute 'set runtimepath+=' .. s:dpp_ext_installer
execute 'set runtimepath+=' .. s:dpp_ext_lazy
execute 'set runtimepath+=' .. s:dpp_ext_toml
execute 'set runtimepath+=' .. s:dpp_prot_git

const s:dpp_base = '~/.cache/dpp/'
const s:dpp_config = '~/.config/vim/dpp.ts'

if s:dpp_base->dpp#min#load_state()
	autocmd User DenopsReady
	\ : echohl WarningMsg
	\ | echomsg 'dpp load_state is failed'
	\ | echohl NONE
	\ | call dpp#make_state(s:dpp_base, s:dpp_config)
endif

autocmd User Dpp:makeStatePost
\ : echohl WarningMsg
\ | echomsg 'dpp make_state() is done'
\ | echohl NONE

filetype indent plugin on

if has('syntax')
	syntax on
endif

colorscheme blue
