#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config focused_border_color "#0096FA"

MONITOR_COUNT=$(bspc query -M | wc -l)
if [ "$MONITOR_COUNT" -eq 1 ]; then
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
elif [ "$MONITOR_COUNT" -eq 2 ]; then
	bspc monitor DP-1 -d 1 2 3 4 5
	bspc monitor eDP-1 -d 6 7 8 9 10
fi
bspc desktop -f 1

# input method module setting
export GTK_IM_MODULE="fcitx5"
export QT_IM_MODULE="fcitx5"
export XMODIFIERS='@im=fcitx5'

export XCURSOR_SIZE=24

fcitx5 &
dunst &
# polybar &
sh ~/.config/polybar/launch_polybar.sh
setxkbmap -option ctrl:nocaps
autorandr --change

xset s 600
xset dpms 600 615 630
xset +dpms
xss-lock -- i3lock --blur 5 --clock --radius=150 --time-size=50 &
xsetroot -cursor_name left_ptr &
