#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true


MONITOR_COUNT=$(bspc query -M | wc -l)
if [ "$MONITOR_COUNT" -eq 1 ]; then
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
elif [ "$MONITOR_COUNT" -eq 2 ]; then
	bspc monitor DP-1 -d 1 2 3 4 5
	bspc monitor eDP-1 -d 6 7 8 9 10
fi

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

fcitx5 &
dunst &
polybar &
setxkbmap -option ctrl:nocaps
autorandr --change
