[[plugins]]
repo = 'numToStr/Comment.nvim'
lua_add = '''
require("Comment").setup()
'''

[[plugins]]
repo = 'Shougo/ddc.vim'
lua_add = '''
require('config.ddc')
'''

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
lua_add = '''
require('config.lsp')
'''
