[tools]
chezmoi = "latest"
ghq = "latest"
helix = "latest"
herdr = "latest"
node = "latest"
pnpm = "latest"
starship = "latest"
github-cli = "latest"
fzf = "latest"
hunk = "latest"
eza = "latest"
zoxide = "latest"
ripgrep = "latest"
fd = "latest"
bat = "latest"
codex = "latest"
yazi = "latest"
