set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc,xterm-256color:RGB,xterm-ghotty:Tc,xterm-ghotty:RGB"

set -g prefix C-g
unbind C-b

bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind o select-pane -t :.+
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -n C-z resize-pane -Z

bind -n S-left previous-window
bind -n S-right next-window

set-option -g mouse on

set-option -g status-position top
