[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
const g:polyglot_disabled = ['sensible', 'ddu-filer', 'ddu-ff']
'''

[[plugins]]
repo = 'ojroques/vim-oscyank'
hook_add = '''
nnoremap <leader>c <Plug>OSCYankOperator
nnoremap <leader>cc <leader>c_
vnoremap <leader>c <Plug>OSCYankVisual
'''

[[plugins]]
repo = 'mhinz/vim-signify'
